[package]
name = "ohttp-relay"
version = "0.0.1"
authors = ["Dan Gould <d@ngould.dev>"]
description = "Relay Oblivious HTTP requests to protect IP metadata"
repository = "https://github.com/payjoin/ohttp-relay"
readme = "README.md"
keywords = ["ohttp", "privacy"]
categories = ["web-programming", "network-programming"]
license = "MITNFA"
edition = "2021"
rust-version = "1.63.0"
resolver = "2"

[dependencies]
futures = "0.3"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-rustls = { version = "0.26", features = ["webpki-roots"] }
hyper-util = { version = "0.1", features = ["full"] }
once_cell = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["net", "codec"] }

[dev-dependencies]
hex = { package = "hex-conservative", version = "0.1.1" }